config/routes.rb
Firstrailsapp::Application.routes.draw do
  resources :teams

  resources :counters

   root 'counters#index'

  

end

app/models/counter.rb
class Counter < ActiveRecord::Base
	belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :counters
	def list_name
		"#{full}, #{short}, #{founded}"
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  before_action :set_counter, only: [:show, :edit, :update, :destroy]

  # GET /counters
  # GET /counters.json
  def index
    @counters = Counter.all
  end

  # GET /counters/1
  # GET /counters/1.json
  def show
  end

  # GET /counters/new
  def new
    @counter = Counter.new
  end

  def landing
	@counter = Counter.last
  end
  
  # GET /counters/1/edit
  def edit
  end

  # POST /counters
  # POST /counters.json
  def create
    @counter = Counter.new(counter_params)

    respond_to do |format|
      if @counter.save
        format.html { redirect_to @counter, notice: 'Counter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @counter }
      else
        format.html { render action: 'new' }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counters/1
  # PATCH/PUT /counters/1.json
  def update
    respond_to do |format|
      if @counter.update(counter_params)
        format.html { redirect_to @counter, notice: 'Counter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counters/1
  # DELETE /counters/1.json
  def destroy
    @counter.destroy
    respond_to do |format|
      format.html { redirect_to counters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_counter
      @counter = Counter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def counter_params
      params.require(:counter).permit(:team_id, :goals)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
	@counters = @team.counters
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render action: 'show', status: :created, location: @team }
      else
        format.html { render action: 'new' }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:full, :short, :founded)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counters_helper.rb
module CountersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/counters/_form.html.erb
<%= form_for(@counter) do |f| %>
  <% if @counter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@counter.errors.count, "error") %> prohibited this counter from being saved:</h2>

      <ul>
      <% @counter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team %><br>
    <%= f.collection_select( :team_id, Team.all, :id, :list_name) %>
  </div>
  <div class="field">
    <%= f.label :goals %><br>
    <%= f.number_field :goals %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/counters/edit.html.erb
<h1>Editing counter</h1>

<%= render 'form' %>

<%= link_to 'Show', @counter %> |
<%= link_to 'Back', counters_path %>

app/views/counters/index.html.erb
<h1>Listing counters</h1>

<%= render 'shared/list_counters' %>

<br>

<%= link_to 'New Counter', new_counter_path %>

app/views/counters/landing.html.erb
<p id="notice"><%= notice %></p>

<p> Greetings Sir. </p>
<p>Latest Team: <%= @counter.team %></p>

<%= form_for(@counter) do |f| %>
  <% if @counter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@counter.errors.count, "error") %> prohibited this counter from being saved:</h2>

      <ul>
      <% @counter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team %><br>
    <%= f.text_field :team %>
  </div>
  <div class="field">
    <%= f.label :goals %><br>
    <%= f.number_field :goals %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/counters/new.html.erb
<h1>New counter</h1>

<%= render 'form' %>

<%= link_to 'Back', counters_path %>

app/views/counters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @counter.team %>
</p>

<p>
  <strong>Goals:</strong>
  <%= @counter.goals %>
</p>

<%= link_to 'Edit', edit_counter_path(@counter) %> |
<%= link_to 'Back', counters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Firstrailsapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_list_counters.html.erb
<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Goals</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @counters.each do |counter| %>
      <tr>
        <td>Team: <%= counter.team %></td>
        <td>Goals: <%= counter.goals %></td>
        <td><%= link_to 'Show', counter %></td>
        <td><%= link_to 'Edit', edit_counter_path(counter) %></td>
        <td><%= link_to 'Destroy', counter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>